import { aiSvelte } from "./ai-shared.ts";
import type { FrameworkEntry } from "./types.ts";

/**
 * `frameworks.svelte` entries for items in ./ai-agent.ts, keyed by item name (`ai-<name>`).
 * Sources live in `src/lib/registry/ai/<name>/` and install to `$lib/components/ai/<name>/`; `dependencies`
 * are inferred by `shadcn-svelte registry build`.
 */
export const entries: Record<string, FrameworkEntry> = {
	"ai-reasoning": aiSvelte("reasoning", [
		"index.ts",
		"reasoning-content.svelte",
		"reasoning-trigger.svelte",
		"reasoning.svelte",
		"use-reasoning.svelte.ts",
	]),
	"ai-chain-of-thought": aiSvelte("chain-of-thought", [
		"chain-of-thought-content.svelte",
		"chain-of-thought-header.svelte",
		"chain-of-thought-image.svelte",
		"chain-of-thought-search-result.svelte",
		"chain-of-thought-search-results.svelte",
		"chain-of-thought-step.svelte",
		"chain-of-thought.svelte",
		"index.ts",
		"use-chain-of-thought.svelte.ts",
	]),
	"ai-tool": aiSvelte("tool", [
		"index.ts",
		"tool-content.svelte",
		"tool-header.svelte",
		"tool-input.svelte",
		"tool-output.svelte",
		"tool-status-badge.svelte",
		"tool.svelte",
		"types.ts",
	]),
	"ai-confirmation": aiSvelte("confirmation", [
		"confirmation-accepted.svelte",
		"confirmation-action.svelte",
		"confirmation-actions.svelte",
		"confirmation-description.svelte",
		"confirmation-rejected.svelte",
		"confirmation-request.svelte",
		"confirmation-title.svelte",
		"confirmation.svelte",
		"index.ts",
		"use-confirmation.svelte.ts",
	]),
	"ai-sources": aiSvelte("sources", [
		"index.ts",
		"source.svelte",
		"sources-content.svelte",
		"sources-trigger.svelte",
		"sources.svelte",
	]),
	"ai-inline-citation": aiSvelte("inline-citation", [
		"index.ts",
		"inline-citation-card-body.svelte",
		"inline-citation-card-trigger.svelte",
		"inline-citation-card.svelte",
		"inline-citation-carousel-content.svelte",
		"inline-citation-carousel-header.svelte",
		"inline-citation-carousel-index.svelte",
		"inline-citation-carousel-item.svelte",
		"inline-citation-carousel-next.svelte",
		"inline-citation-carousel-prev.svelte",
		"inline-citation-carousel.svelte",
		"inline-citation-quote.svelte",
		"inline-citation-source.svelte",
		"inline-citation-text.svelte",
		"inline-citation.svelte",
	]),
	"ai-plan": aiSvelte("plan", [
		"index.ts",
		"plan-action.svelte",
		"plan-content.svelte",
		"plan-description.svelte",
		"plan-footer.svelte",
		"plan-header.svelte",
		"plan-title.svelte",
		"plan-trigger.svelte",
		"plan.svelte",
		"use-plan.svelte.ts",
	]),
	"ai-task": aiSvelte("task", [
		"index.ts",
		"task-content.svelte",
		"task-item-file.svelte",
		"task-item.svelte",
		"task-trigger.svelte",
		"task.svelte",
	]),
	"ai-queue": aiSvelte("queue", [
		"index.ts",
		"queue-item-action.svelte",
		"queue-item-actions.svelte",
		"queue-item-attachment.svelte",
		"queue-item-content.svelte",
		"queue-item-description.svelte",
		"queue-item-file.svelte",
		"queue-item-image.svelte",
		"queue-item-indicator.svelte",
		"queue-item.svelte",
		"queue-list.svelte",
		"queue-section-content.svelte",
		"queue-section-label.svelte",
		"queue-section-trigger.svelte",
		"queue-section.svelte",
		"queue.svelte",
		"types.ts",
	]),
	"ai-checkpoint": aiSvelte("checkpoint", [
		"checkpoint-icon.svelte",
		"checkpoint-trigger.svelte",
		"checkpoint.svelte",
		"index.ts",
	]),
};
