import { aiVue } from "./ai-shared.ts";
import type { FrameworkEntry } from "./types.ts";

/**
 * `frameworks.vue` entries for items in ./ai-code.ts, keyed by item name (`ai-<name>`).
 * Files live in `registry/components/ai/<name>/` and install to `components/ai/<name>/`.
 */
export const entries: Record<string, FrameworkEntry> = {
	"ai-agent": aiVue(
		"agent",
		[
			"Agent.vue",
			"AgentContent.vue",
			"AgentHeader.vue",
			"AgentInstructions.vue",
			"AgentOutput.vue",
			"AgentTool.vue",
			"AgentTools.vue",
		],
		["@lucide/vue", "@vueuse/core", "reka-ui"],
	),
	"ai-artifact": aiVue(
		"artifact",
		[
			"Artifact.vue",
			"ArtifactAction.vue",
			"ArtifactActions.vue",
			"ArtifactClose.vue",
			"ArtifactContent.vue",
			"ArtifactDescription.vue",
			"ArtifactHeader.vue",
			"ArtifactTitle.vue",
		],
		["@lucide/vue"],
	),
	"ai-code-block": aiVue(
		"code-block",
		[
			"CodeBlock.vue",
			"CodeBlockActions.vue",
			"CodeBlockContainer.vue",
			"CodeBlockContent.vue",
			"CodeBlockCopyButton.vue",
			"CodeBlockFilename.vue",
			"CodeBlockHeader.vue",
			"CodeBlockLanguageSelector.vue",
			"CodeBlockLanguageSelectorContent.vue",
			"CodeBlockLanguageSelectorItem.vue",
			"CodeBlockLanguageSelectorTrigger.vue",
			"CodeBlockLanguageSelectorValue.vue",
			"CodeBlockTitle.vue",
			"context.ts",
			"utils.ts",
		],
		["@lucide/vue", "@vueuse/core", "reka-ui", "shiki"],
	),
	"ai-commit": aiVue(
		"commit",
		[
			"Commit.vue",
			"CommitActions.vue",
			"CommitAuthor.vue",
			"CommitAuthorAvatar.vue",
			"CommitContent.vue",
			"CommitCopyButton.vue",
			"CommitFile.vue",
			"CommitFileAdditions.vue",
			"CommitFileChanges.vue",
			"CommitFileDeletions.vue",
			"CommitFileIcon.vue",
			"CommitFileInfo.vue",
			"CommitFilePath.vue",
			"CommitFileStatus.vue",
			"CommitFiles.vue",
			"CommitFilesToggle.vue",
			"CommitHash.vue",
			"CommitHeader.vue",
			"CommitInfo.vue",
			"CommitMessage.vue",
			"CommitMetadata.vue",
			"CommitSeparator.vue",
			"CommitTimestamp.vue",
		],
		["@lucide/vue", "@vueuse/core", "reka-ui"],
	),
	"ai-environment-variables": aiVue(
		"environment-variables",
		[
			"EnvironmentVariable.vue",
			"EnvironmentVariableCopyButton.vue",
			"EnvironmentVariableGroup.vue",
			"EnvironmentVariableName.vue",
			"EnvironmentVariableRequired.vue",
			"EnvironmentVariableValue.vue",
			"EnvironmentVariables.vue",
			"EnvironmentVariablesContent.vue",
			"EnvironmentVariablesHeader.vue",
			"EnvironmentVariablesTitle.vue",
			"EnvironmentVariablesToggle.vue",
			"context.ts",
		],
		["@lucide/vue", "@vueuse/core"],
	),
	"ai-file-tree": aiVue(
		"file-tree",
		[
			"FileTree.vue",
			"FileTreeActions.vue",
			"FileTreeFile.vue",
			"FileTreeFolder.vue",
			"FileTreeIcon.vue",
			"FileTreeName.vue",
			"context.ts",
		],
		["@lucide/vue", "@vueuse/core"],
	),
	"ai-jsx-preview": aiVue(
		"jsx-preview",
		[
			"JSXPreview.vue",
			"JSXPreviewContent.ts",
			"JSXPreviewError.vue",
			"context.ts",
			"parser.ts",
		],
		["@lucide/vue"],
	),
	"ai-package-info": aiVue(
		"package-info",
		[
			"PackageInfo.vue",
			"PackageInfoChangeType.vue",
			"PackageInfoContent.vue",
			"PackageInfoDependencies.vue",
			"PackageInfoDependency.vue",
			"PackageInfoDescription.vue",
			"PackageInfoHeader.vue",
			"PackageInfoName.vue",
			"PackageInfoVersion.vue",
			"context.ts",
		],
		["@lucide/vue"],
	),
};
