import { aiVue } from "./ai-shared.ts";
import type { FrameworkEntry } from "./types.ts";

/**
 * `frameworks.vue` entries for items in ./ai-chat.ts, keyed by item name (`ai-<name>`).
 * Files live in `registry/components/ai/<name>/` and install to `components/ai/<name>/`.
 */
export const entries: Record<string, FrameworkEntry> = {
	"ai-conversation": aiVue(
		"conversation",
		[
			"Conversation.vue",
			"ConversationContent.vue",
			"ConversationDownload.vue",
			"ConversationEmptyState.vue",
			"ConversationItem.vue",
			"ConversationScrollButton.vue",
			"utils.ts",
		],
		["ai", "@lucide/vue"],
	),
	"ai-message": aiVue(
		"message",
		[
			"Message.vue",
			"MessageAction.vue",
			"MessageActions.vue",
			"MessageBranch.vue",
			"MessageBranchContent.vue",
			"MessageBranchNext.vue",
			"MessageBranchPage.vue",
			"MessageBranchPrevious.vue",
			"MessageBranchSelector.vue",
			"MessageContent.vue",
			"MessageResponse.vue",
			"MessageToolbar.vue",
			"context.ts",
		],
		["ai", "@lucide/vue", "vue-stream-markdown"],
	),
	"ai-prompt-input": aiVue(
		"prompt-input",
		[
			"PromptInput.vue",
			"PromptInputActionAddAttachments.vue",
			"PromptInputActionAddScreenshot.vue",
			"PromptInputActionMenu.vue",
			"PromptInputActionMenuContent.vue",
			"PromptInputActionMenuItem.vue",
			"PromptInputActionMenuTrigger.vue",
			"PromptInputBody.vue",
			"PromptInputButton.vue",
			"PromptInputCommand.vue",
			"PromptInputCommandEmpty.vue",
			"PromptInputCommandGroup.vue",
			"PromptInputCommandInput.vue",
			"PromptInputCommandItem.vue",
			"PromptInputCommandList.vue",
			"PromptInputCommandSeparator.vue",
			"PromptInputFooter.vue",
			"PromptInputHeader.vue",
			"PromptInputHoverCard.vue",
			"PromptInputHoverCardContent.vue",
			"PromptInputHoverCardTrigger.vue",
			"PromptInputProvider.vue",
			"PromptInputSelect.vue",
			"PromptInputSelectContent.vue",
			"PromptInputSelectItem.vue",
			"PromptInputSelectTrigger.vue",
			"PromptInputSelectValue.vue",
			"PromptInputSubmit.vue",
			"PromptInputTab.vue",
			"PromptInputTabBody.vue",
			"PromptInputTabItem.vue",
			"PromptInputTabLabel.vue",
			"PromptInputTabsList.vue",
			"PromptInputTextarea.vue",
			"PromptInputTools.vue",
			"context.ts",
			"screenshot.ts",
			"types.ts",
		],
		["ai", "nanoid", "@lucide/vue", "reka-ui", "@vueuse/core"],
	),
	"ai-suggestion": aiVue("suggestion", ["Suggestion.vue", "Suggestions.vue"]),
	"ai-attachments": aiVue(
		"attachments",
		[
			"Attachment.vue",
			"AttachmentEmpty.vue",
			"AttachmentHoverCard.vue",
			"AttachmentHoverCardContent.vue",
			"AttachmentHoverCardTrigger.vue",
			"AttachmentInfo.vue",
			"AttachmentPreview.vue",
			"AttachmentRemove.vue",
			"Attachments.vue",
			"context.ts",
			"types.ts",
			"utils.ts",
		],
		["ai", "@lucide/vue", "reka-ui", "@vueuse/core"],
	),
	"ai-model-selector": aiVue(
		"model-selector",
		[
			"ModelSelector.vue",
			"ModelSelectorContent.vue",
			"ModelSelectorDialog.vue",
			"ModelSelectorEmpty.vue",
			"ModelSelectorGroup.vue",
			"ModelSelectorInput.vue",
			"ModelSelectorItem.vue",
			"ModelSelectorList.vue",
			"ModelSelectorLogo.vue",
			"ModelSelectorLogoGroup.vue",
			"ModelSelectorName.vue",
			"ModelSelectorSeparator.vue",
			"ModelSelectorShortcut.vue",
			"ModelSelectorTrigger.vue",
		],
		["reka-ui"],
	),
	"ai-context": aiVue(
		"context",
		[
			"Context.vue",
			"ContextCacheUsage.vue",
			"ContextContent.vue",
			"ContextContentBody.vue",
			"ContextContentFooter.vue",
			"ContextContentHeader.vue",
			"ContextIcon.vue",
			"ContextInputUsage.vue",
			"ContextOutputUsage.vue",
			"ContextReasoningUsage.vue",
			"ContextTrigger.vue",
			"TokensWithCost.vue",
			"context.ts",
		],
		["ai", "tokenlens", "reka-ui"],
	),
	"ai-shimmer": aiVue("shimmer", ["Shimmer.vue"], ["motion-v"]),
};
