import { aiSvelte } from "./ai-shared.ts";
import type { FrameworkEntry } from "./types.ts";

/**
 * `frameworks.svelte` entries for items in ./ai-code.ts, keyed by item name (`ai-<name>`).
 * Sources live in `src/lib/registry/ai/<name>/`; sibling AI imports are relative.
 */
export const entries: Record<string, FrameworkEntry> = {
	"ai-agent": aiSvelte("agent", [
		"agent-content.svelte",
		"agent-header.svelte",
		"agent-instructions.svelte",
		"agent-output.svelte",
		"agent-tool.svelte",
		"agent-tools.svelte",
		"agent.svelte",
		"use-agent.svelte.ts",
		"index.ts",
	]),
	"ai-artifact": aiSvelte("artifact", [
		"artifact-action.svelte",
		"artifact-actions.svelte",
		"artifact-close.svelte",
		"artifact-content.svelte",
		"artifact-description.svelte",
		"artifact-header.svelte",
		"artifact-title.svelte",
		"artifact.svelte",
		"index.ts",
	]),
	"ai-code-block": aiSvelte("code-block", [
		"code-block-actions.svelte",
		"code-block-content.svelte",
		"code-block-copy-button.svelte",
		"code-block-filename.svelte",
		"code-block-header.svelte",
		"code-block-language-selector-trigger.svelte",
		"code-block-title.svelte",
		"code-block.svelte",
		"use-code-block.svelte.ts",
		"utils.ts",
		"index.ts",
	]),
	"ai-commit": aiSvelte("commit", [
		"commit-actions.svelte",
		"commit-author-avatar.svelte",
		"commit-author.svelte",
		"commit-content.svelte",
		"commit-copy-button.svelte",
		"commit-file-additions.svelte",
		"commit-file-changes.svelte",
		"commit-file-deletions.svelte",
		"commit-file-icon.svelte",
		"commit-file-info.svelte",
		"commit-file-path.svelte",
		"commit-file-status.svelte",
		"commit-file.svelte",
		"commit-files-toggle.svelte",
		"commit-files.svelte",
		"commit-hash.svelte",
		"commit-header.svelte",
		"commit-info.svelte",
		"commit-message.svelte",
		"commit-metadata.svelte",
		"commit-separator.svelte",
		"commit-timestamp.svelte",
		"commit.svelte",
		"index.ts",
	]),
	"ai-environment-variables": aiSvelte("environment-variables", [
		"environment-variable-copy-button.svelte",
		"environment-variable-group.svelte",
		"environment-variable-name.svelte",
		"environment-variable-required.svelte",
		"environment-variable-value.svelte",
		"environment-variable.svelte",
		"environment-variables-content.svelte",
		"environment-variables-header.svelte",
		"environment-variables-title.svelte",
		"environment-variables-toggle.svelte",
		"environment-variables.svelte",
		"use-environment-variables.svelte.ts",
		"index.ts",
	]),
	"ai-file-tree": aiSvelte("file-tree", [
		"file-tree-actions.svelte",
		"file-tree-file.svelte",
		"file-tree-folder.svelte",
		"file-tree-icon.svelte",
		"file-tree-name.svelte",
		"file-tree.svelte",
		"use-file-tree.svelte.ts",
		"index.ts",
	]),
	"ai-jsx-preview": aiSvelte("jsx-preview", [
		"jsx-preview-content.svelte",
		"jsx-preview-error.svelte",
		"jsx-preview-nodes.svelte",
		"jsx-preview.svelte",
		"parser.ts",
		"use-jsx-preview.svelte.ts",
		"index.ts",
	]),
	"ai-package-info": aiSvelte("package-info", [
		"package-info-change-type.svelte",
		"package-info-content.svelte",
		"package-info-dependencies.svelte",
		"package-info-dependency.svelte",
		"package-info-description.svelte",
		"package-info-header.svelte",
		"package-info-name.svelte",
		"package-info-version.svelte",
		"package-info.svelte",
		"use-package-info.svelte.ts",
		"index.ts",
	]),
};
