import { aiSvelte } from "./ai-shared.ts";
import type { FrameworkEntry } from "./types.ts";

/**
 * `frameworks.svelte` entries for items in ./ai-chat.ts, keyed by item name (`ai-<name>`).
 * Sources live in `src/lib/registry/ai/<name>/` and install to `$lib/components/ai/<name>/`; `dependencies`
 * are inferred by `shadcn-svelte registry build`.
 */
export const entries: Record<string, FrameworkEntry> = {
	"ai-conversation": aiSvelte("conversation", [
		"conversation-content.svelte",
		"conversation-download.svelte",
		"conversation-empty-state.svelte",
		"conversation-item.svelte",
		"conversation-scroll-button.svelte",
		"conversation.svelte",
		"index.ts",
		"utils.ts",
	]),
	"ai-message": aiSvelte("message", [
		"index.ts",
		"message-action.svelte",
		"message-actions.svelte",
		"message-branch-content.svelte",
		"message-branch-next.svelte",
		"message-branch-page.svelte",
		"message-branch-previous.svelte",
		"message-branch-selector.svelte",
		"message-branch.svelte",
		"message-content.svelte",
		"message-response.svelte",
		"message-toolbar.svelte",
		"message.svelte",
		"use-message.svelte.ts",
	]),
	"ai-prompt-input": aiSvelte("prompt-input", [
		"index.ts",
		"prompt-input-action-add-attachments.svelte",
		"prompt-input-action-add-screenshot.svelte",
		"prompt-input-action-menu-content.svelte",
		"prompt-input-action-menu-item.svelte",
		"prompt-input-action-menu-trigger.svelte",
		"prompt-input-action-menu.svelte",
		"prompt-input-body.svelte",
		"prompt-input-button.svelte",
		"prompt-input-command-empty.svelte",
		"prompt-input-command-group.svelte",
		"prompt-input-command-input.svelte",
		"prompt-input-command-item.svelte",
		"prompt-input-command-list.svelte",
		"prompt-input-command-separator.svelte",
		"prompt-input-command.svelte",
		"prompt-input-footer.svelte",
		"prompt-input-header.svelte",
		"prompt-input-hover-card-content.svelte",
		"prompt-input-hover-card-trigger.svelte",
		"prompt-input-hover-card.svelte",
		"prompt-input-provider.svelte",
		"prompt-input-select-content.svelte",
		"prompt-input-select-item.svelte",
		"prompt-input-select-trigger.svelte",
		"prompt-input-select-value.svelte",
		"prompt-input-select.svelte",
		"prompt-input-submit.svelte",
		"prompt-input-tab-body.svelte",
		"prompt-input-tab-item.svelte",
		"prompt-input-tab-label.svelte",
		"prompt-input-tab.svelte",
		"prompt-input-tabs-list.svelte",
		"prompt-input-textarea.svelte",
		"prompt-input-tools.svelte",
		"prompt-input.svelte",
		"screenshot.ts",
		"types.ts",
		"use-prompt-input.svelte.ts",
	]),
	"ai-suggestion": aiSvelte("suggestion", [
		"index.ts",
		"suggestion.svelte",
		"suggestions.svelte",
	]),
	"ai-attachments": aiSvelte("attachments", [
		"attachment-empty.svelte",
		"attachment-hover-card-content.svelte",
		"attachment-hover-card-trigger.svelte",
		"attachment-hover-card.svelte",
		"attachment-info.svelte",
		"attachment-preview.svelte",
		"attachment-remove.svelte",
		"attachment.svelte",
		"attachments.svelte",
		"index.ts",
		"types.ts",
		"use-attachments.svelte.ts",
		"utils.ts",
	]),
	"ai-model-selector": aiSvelte("model-selector", [
		"index.ts",
		"model-selector-content.svelte",
		"model-selector-dialog.svelte",
		"model-selector-empty.svelte",
		"model-selector-group.svelte",
		"model-selector-input.svelte",
		"model-selector-item.svelte",
		"model-selector-list.svelte",
		"model-selector-logo-group.svelte",
		"model-selector-logo.svelte",
		"model-selector-name.svelte",
		"model-selector-separator.svelte",
		"model-selector-shortcut.svelte",
		"model-selector-trigger.svelte",
		"model-selector.svelte",
	]),
	"ai-context": aiSvelte("context", [
		"context-cache-usage.svelte",
		"context-content-body.svelte",
		"context-content-footer.svelte",
		"context-content-header.svelte",
		"context-content.svelte",
		"context-icon.svelte",
		"context-input-usage.svelte",
		"context-output-usage.svelte",
		"context-reasoning-usage.svelte",
		"context-trigger.svelte",
		"context.svelte",
		"index.ts",
		"tokens-with-cost.svelte",
		"use-context.svelte.ts",
	]),
	"ai-shimmer": aiSvelte("shimmer", ["index.ts", "shimmer.svelte"]),
};
