import { aiSvelte } from "./ai-shared.ts";
import type { FrameworkEntry } from "./types.ts";

/**
 * `frameworks.svelte` entries for items in ./ai-runtime.ts, keyed by item name (`ai-<name>`).
 * Sources live in `src/lib/registry/ai/<name>/` and install to `$lib/components/ai/<name>/`; `dependencies`
 * are inferred by `shadcn-svelte registry build`.
 */
export const entries: Record<string, FrameworkEntry> = {
	"ai-sandbox": aiSvelte("sandbox", [
		"index.ts",
		"sandbox-content.svelte",
		"sandbox-header.svelte",
		"sandbox-status-badge.svelte",
		"sandbox-tab-content.svelte",
		"sandbox-tabs-bar.svelte",
		"sandbox-tabs-list.svelte",
		"sandbox-tabs-trigger.svelte",
		"sandbox-tabs.svelte",
		"sandbox.svelte",
	]),
	"ai-schema-display": aiSvelte("schema-display", [
		"index.ts",
		"schema-display-body.svelte",
		"schema-display-content.svelte",
		"schema-display-description.svelte",
		"schema-display-example.svelte",
		"schema-display-header.svelte",
		"schema-display-method.svelte",
		"schema-display-parameter.svelte",
		"schema-display-parameters.svelte",
		"schema-display-path.svelte",
		"schema-display-property.svelte",
		"schema-display-request.svelte",
		"schema-display-response.svelte",
		"schema-display-section.svelte",
		"schema-display.svelte",
		"use-schema-display.svelte.ts",
	]),
	"ai-snippet": aiSvelte("snippet", [
		"index.ts",
		"snippet-addon.svelte",
		"snippet-copy-button.svelte",
		"snippet-input.svelte",
		"snippet-text.svelte",
		"snippet.svelte",
		"use-snippet.svelte.ts",
	]),
	"ai-stack-trace": aiSvelte("stack-trace", [
		"index.ts",
		"stack-trace-actions.svelte",
		"stack-trace-content.svelte",
		"stack-trace-copy-button.svelte",
		"stack-trace-error-message.svelte",
		"stack-trace-error-type.svelte",
		"stack-trace-error.svelte",
		"stack-trace-expand-button.svelte",
		"stack-trace-frames.svelte",
		"stack-trace-header.svelte",
		"stack-trace.svelte",
		"use-stack-trace.svelte.ts",
	]),
	"ai-terminal": aiSvelte("terminal", [
		"index.ts",
		"terminal-actions.svelte",
		"terminal-clear-button.svelte",
		"terminal-content.svelte",
		"terminal-copy-button.svelte",
		"terminal-header.svelte",
		"terminal-status.svelte",
		"terminal-title.svelte",
		"terminal.svelte",
		"use-terminal.svelte.ts",
	]),
	"ai-test-results": aiSvelte("test-results", [
		"index.ts",
		"test-duration.svelte",
		"test-error-message.svelte",
		"test-error-stack.svelte",
		"test-error.svelte",
		"test-name.svelte",
		"test-results-content.svelte",
		"test-results-duration.svelte",
		"test-results-header.svelte",
		"test-results-progress.svelte",
		"test-results-summary.svelte",
		"test-results.svelte",
		"test-status.svelte",
		"test-suite-content.svelte",
		"test-suite-name.svelte",
		"test-suite-stats.svelte",
		"test-suite.svelte",
		"test.svelte",
		"use-test-results.svelte.ts",
	]),
	"ai-web-preview": aiSvelte("web-preview", [
		"index.ts",
		"use-web-preview.svelte.ts",
		"web-preview-body.svelte",
		"web-preview-console.svelte",
		"web-preview-navigation-button.svelte",
		"web-preview-navigation.svelte",
		"web-preview-url.svelte",
		"web-preview.svelte",
	]),
};
