import type { FrameworkEntry } from "./types.ts";

/** `frameworks.vue` entries for items in ./navigation.ts, keyed by item name (owned by the vue worker). */
export const entries: Record<string, FrameworkEntry> = {
	tabs: {
		files: [
			{ path: "registry/ui/tabs/Tabs.vue" },
			{ path: "registry/ui/tabs/TabsContent.vue" },
			{ path: "registry/ui/tabs/TabsList.vue" },
			{ path: "registry/ui/tabs/TabsTrigger.vue" },
			{ path: "registry/ui/tabs/index.ts" },
		],
		dependencies: ["reka-ui", "class-variance-authority", "@vueuse/core"],
	},
	breadcrumb: {
		files: [
			{ path: "registry/ui/breadcrumb/Breadcrumb.vue" },
			{ path: "registry/ui/breadcrumb/BreadcrumbEllipsis.vue" },
			{ path: "registry/ui/breadcrumb/BreadcrumbItem.vue" },
			{ path: "registry/ui/breadcrumb/BreadcrumbLink.vue" },
			{ path: "registry/ui/breadcrumb/BreadcrumbList.vue" },
			{ path: "registry/ui/breadcrumb/BreadcrumbPage.vue" },
			{ path: "registry/ui/breadcrumb/BreadcrumbSeparator.vue" },
			{ path: "registry/ui/breadcrumb/index.ts" },
		],
		dependencies: ["reka-ui"],
	},
	pagination: {
		files: [
			{ path: "registry/ui/pagination/Pagination.vue" },
			{ path: "registry/ui/pagination/PaginationContent.vue" },
			{ path: "registry/ui/pagination/PaginationEllipsis.vue" },
			{ path: "registry/ui/pagination/PaginationFirst.vue" },
			{ path: "registry/ui/pagination/PaginationItem.vue" },
			{ path: "registry/ui/pagination/PaginationLast.vue" },
			{ path: "registry/ui/pagination/PaginationNext.vue" },
			{ path: "registry/ui/pagination/PaginationPrevious.vue" },
			{ path: "registry/ui/pagination/index.ts" },
		],
		dependencies: ["reka-ui", "@vueuse/core"],
	},
	"dropdown-menu": {
		files: [
			{ path: "registry/ui/dropdown-menu/DropdownMenu.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuCheckboxItem.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuContent.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuGroup.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuItem.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuLabel.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuRadioGroup.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuRadioItem.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuSeparator.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuShortcut.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuSub.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuSubContent.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuSubTrigger.vue" },
			{ path: "registry/ui/dropdown-menu/DropdownMenuTrigger.vue" },
			{ path: "registry/ui/dropdown-menu/index.ts" },
		],
		dependencies: ["reka-ui", "@vueuse/core"],
	},
	"context-menu": {
		files: [
			{ path: "registry/ui/context-menu/ContextMenu.vue" },
			{ path: "registry/ui/context-menu/ContextMenuCheckboxItem.vue" },
			{ path: "registry/ui/context-menu/ContextMenuContent.vue" },
			{ path: "registry/ui/context-menu/ContextMenuGroup.vue" },
			{ path: "registry/ui/context-menu/ContextMenuItem.vue" },
			{ path: "registry/ui/context-menu/ContextMenuLabel.vue" },
			{ path: "registry/ui/context-menu/ContextMenuPortal.vue" },
			{ path: "registry/ui/context-menu/ContextMenuRadioGroup.vue" },
			{ path: "registry/ui/context-menu/ContextMenuRadioItem.vue" },
			{ path: "registry/ui/context-menu/ContextMenuSeparator.vue" },
			{ path: "registry/ui/context-menu/ContextMenuShortcut.vue" },
			{ path: "registry/ui/context-menu/ContextMenuSub.vue" },
			{ path: "registry/ui/context-menu/ContextMenuSubContent.vue" },
			{ path: "registry/ui/context-menu/ContextMenuSubTrigger.vue" },
			{ path: "registry/ui/context-menu/ContextMenuTrigger.vue" },
			{ path: "registry/ui/context-menu/index.ts" },
		],
		dependencies: ["reka-ui", "@vueuse/core"],
	},
	menubar: {
		files: [
			{ path: "registry/ui/menubar/Menubar.vue" },
			{ path: "registry/ui/menubar/MenubarCheckboxItem.vue" },
			{ path: "registry/ui/menubar/MenubarContent.vue" },
			{ path: "registry/ui/menubar/MenubarGroup.vue" },
			{ path: "registry/ui/menubar/MenubarItem.vue" },
			{ path: "registry/ui/menubar/MenubarLabel.vue" },
			{ path: "registry/ui/menubar/MenubarMenu.vue" },
			{ path: "registry/ui/menubar/MenubarRadioGroup.vue" },
			{ path: "registry/ui/menubar/MenubarRadioItem.vue" },
			{ path: "registry/ui/menubar/MenubarSeparator.vue" },
			{ path: "registry/ui/menubar/MenubarShortcut.vue" },
			{ path: "registry/ui/menubar/MenubarSub.vue" },
			{ path: "registry/ui/menubar/MenubarSubContent.vue" },
			{ path: "registry/ui/menubar/MenubarSubTrigger.vue" },
			{ path: "registry/ui/menubar/MenubarTrigger.vue" },
			{ path: "registry/ui/menubar/index.ts" },
		],
		dependencies: ["reka-ui", "@vueuse/core"],
		registryDependencies: [],
	},
	"navigation-menu": {
		files: [
			{ path: "registry/ui/navigation-menu/NavigationMenu.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuContent.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuIndicator.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuItem.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuLink.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuList.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuTrigger.vue" },
			{ path: "registry/ui/navigation-menu/NavigationMenuViewport.vue" },
			{ path: "registry/ui/navigation-menu/index.ts" },
		],
		dependencies: ["reka-ui", "class-variance-authority", "@vueuse/core"],
	},
	command: {
		files: [
			{ path: "registry/ui/command/Command.vue" },
			{ path: "registry/ui/command/CommandDialog.vue" },
			{ path: "registry/ui/command/CommandEmpty.vue" },
			{ path: "registry/ui/command/CommandGroup.vue" },
			{ path: "registry/ui/command/CommandInput.vue" },
			{ path: "registry/ui/command/CommandItem.vue" },
			{ path: "registry/ui/command/CommandList.vue" },
			{ path: "registry/ui/command/CommandSeparator.vue" },
			{ path: "registry/ui/command/CommandShortcut.vue" },
			{ path: "registry/ui/command/index.ts" },
		],
		dependencies: ["reka-ui", "@vueuse/core"],
	},
	sidebar: {
		files: [
			{ path: "registry/ui/sidebar/Sidebar.vue" },
			{ path: "registry/ui/sidebar/SidebarContent.vue" },
			{ path: "registry/ui/sidebar/SidebarFooter.vue" },
			{ path: "registry/ui/sidebar/SidebarGroup.vue" },
			{ path: "registry/ui/sidebar/SidebarGroupAction.vue" },
			{ path: "registry/ui/sidebar/SidebarGroupContent.vue" },
			{ path: "registry/ui/sidebar/SidebarGroupLabel.vue" },
			{ path: "registry/ui/sidebar/SidebarHeader.vue" },
			{ path: "registry/ui/sidebar/SidebarInput.vue" },
			{ path: "registry/ui/sidebar/SidebarInset.vue" },
			{ path: "registry/ui/sidebar/SidebarMenu.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuAction.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuBadge.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuButton.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuButtonChild.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuItem.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuSkeleton.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuSub.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuSubButton.vue" },
			{ path: "registry/ui/sidebar/SidebarMenuSubItem.vue" },
			{ path: "registry/ui/sidebar/SidebarProvider.vue" },
			{ path: "registry/ui/sidebar/SidebarRail.vue" },
			{ path: "registry/ui/sidebar/SidebarSeparator.vue" },
			{ path: "registry/ui/sidebar/SidebarTrigger.vue" },
			{ path: "registry/ui/sidebar/utils.ts" },
			{ path: "registry/ui/sidebar/index.ts" },
		],
		dependencies: ["reka-ui", "class-variance-authority", "@vueuse/core"],
		registryDependencies: [
			"button",
			"input",
			"separator",
			"sheet",
			"skeleton",
			"tooltip",
		],
	},
	// shadcn-vue ships no use-mobile hook: the sidebar provider uses `useMediaQuery` from @vueuse/core.
	"use-mobile": { skip: true },
};
